"""0001_init

Revision ID: 27cd61d87298
Revises: 
Create Date: 2026-09-08 15:41:50.849818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27cd61d87298'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('ts', sa.String(length=19), nullable=False),
    sa.Column('ack', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('calc_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.String(length=19), nullable=False),
    sa.Column('calc_type', sa.String(length=24), nullable=False),
    sa.Column('system', sa.String(length=32), nullable=False),
    sa.Column('input_json', sa.String(length=2000), nullable=False),
    sa.Column('output_json', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calc_type_ts', 'calc_logs', ['calc_type', 'ts'], unique=False)
    op.create_table('coarse_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=True),
    sa.Column('intercept', sa.Float(), nullable=False),
    sa.Column('coefs', sa.JSON(), nullable=True),
    sa.Column('means', sa.JSON(), nullable=True),
    sa.Column('stds', sa.JSON(), nullable=True),
    sa.Column('std_coef', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('impute_means', sa.JSON(), nullable=True),
    sa.Column('pls_A', sa.Integer(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('tolerance', sa.Float(), nullable=False),
    sa.Column('train_range', sa.String(length=16), nullable=False),
    sa.Column('trained_at', sa.String(length=19), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heavy_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.String(length=19), nullable=False),
    sa.Column('rho', sa.Float(), nullable=False),
    sa.Column('ash_content', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.String(length=19), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.String(length=19), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regression_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_type', sa.String(length=8), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('r_squared', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('data_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=19), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('coal_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.String(length=19), nullable=False),
    sa.Column('system', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('ash_content', sa.Float(), nullable=True),
    sa.Column('coal_amount', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('level', sa.Float(), nullable=True),
    sa.Column('raw_ash', sa.Float(), nullable=True),
    sa.Column('moisture', sa.Float(), nullable=True),
    sa.Column('belt', sa.String(length=16), nullable=True),
    sa.Column('sysA', sa.Integer(), nullable=False),
    sa.Column('sysB', sa.Integer(), nullable=False),
    sa.Column('sys401', sa.Integer(), nullable=False),
    sa.Column('sys402', sa.Integer(), nullable=False),
    sa.Column('desliming473', sa.Integer(), nullable=False),
    sa.Column('desliming474', sa.Integer(), nullable=False),
    sa.Column('is_stoppage', sa.Integer(), nullable=False),
    sa.Column('mining_face', sa.String(length=64), nullable=True),
    sa.Column('filter_press_running', sa.Integer(), nullable=True),
    sa.Column('influence_value', sa.Float(), nullable=True),
    sa.Column('annotation', sa.String(length=64), nullable=True),
    sa.Column('predicted_ash', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'ts', 'system', name='uq_coal_cat_ts_sys')
    )
    op.create_index('ix_coal_cat_ts', 'coal_records', ['category', 'ts'], unique=False)
    op.create_index('ix_coal_ts', 'coal_records', ['ts'], unique=False)
    op.create_table('coarse_model_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('trained_at', sa.String(length=19), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('tolerance', sa.Float(), nullable=False),
    sa.Column('train_range', sa.String(length=16), nullable=False),
    sa.Column('production', sa.String(length=8), nullable=False),
    sa.Column('mlr_r2', sa.Float(), nullable=True),
    sa.Column('pls_r2', sa.Float(), nullable=True),
    sa.Column('mlr_q2', sa.Float(), nullable=True),
    sa.Column('pls_q2', sa.Float(), nullable=True),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['coarse_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coarse_model_history')
    op.drop_index('ix_coal_ts', table_name='coal_records')
    op.drop_index('ix_coal_cat_ts', table_name='coal_records')
    op.drop_table('coal_records')
    op.drop_table('settings')
    op.drop_table('regression_models')
    op.drop_table('manual_entries')
    op.drop_table('import_logs')
    op.drop_table('heavy_samples')
    op.drop_table('coarse_models')
    op.drop_index('ix_calc_type_ts', table_name='calc_logs')
    op.drop_table('calc_logs')
    op.drop_table('auto_state')
    op.drop_table('alerts')
    # ### end Alembic commands ###
